// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// nw_weight
NumericVector nw_weight(NumericMatrix hhat, int nobs, int num_exog, int nlag);
RcppExport SEXP _lpirfs_nw_weight(SEXP hhatSEXP, SEXP nobsSEXP, SEXP num_exogSEXP, SEXP nlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type hhat(hhatSEXP);
    Rcpp::traits::input_parameter< int >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< int >::type num_exog(num_exogSEXP);
    Rcpp::traits::input_parameter< int >::type nlag(nlagSEXP);
    rcpp_result_gen = Rcpp::wrap(nw_weight(hhat, nobs, num_exog, nlag));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lpirfs_nw_weight", (DL_FUNC) &_lpirfs_nw_weight, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_lpirfs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
